### ISSUE TITLE
PtP code review comments

### ISSUE THREAD

**Issue by Aidan-bn** [michael-duke/Portfolio#12]
- Kindly try use background-blend-mode: multiply and backdrop-filter: blur(7px); to get the blur effect
- The task is awesome and good look.
- code is neat

**Comment by michael-duke** [comment]
Thank you for your feedback @muskan2532150 , @Aidan-bn , and @WalterOkumu I have kept my background and continue to use the gradient generator, until I figure out well the mix-blend property. 😄
