### ISSUE TITLE
HIDE AND SEEK 

### ISSUE THREAD

**Issue by peterboro** [michael-duke/Portfolio#16]
## Bugs: hide-and-seek
In this exercise I have:
- Located a bug using manual QA methods.
- Understand the importance of thoughtful, intentional problem-solving.
- Identified how developer tools are used in debugging front-end code.
- _**Bugs found**_
   - The issue was the `onPopup` was not accessing the zero-based index project list array.
   - Another one was the `resetForm` function was not removing the local storage form data.

**Comment by michael-duke** [comment]
Great pointing out the issues @peterboro, thank you for collaborating with me this week

**Comment by peterboro** [comment]
Thank you for your collaboration as well.
