### ISSUE TITLE
MIlestone 6 Portfolio: Application deploy

### ISSUE THREAD

**Issue by michael-duke** [michael-duke/Portfolio#7]
## Portfolio milestone 6 : Application deploy

In this milestone I :
- Use GitHub Pages to deploy web pages.
- Demonstrate ability to ask clarifying questions about ambiguous requirements.
- Checked the online version of my portfolio and made sure that the page works properly.
- Update the README of my repository to include a link to the online version.

I have deployed my app earlier, so I opened an issue with this link to the online version of _[My Portfolio](https://michael-duke.github.io/Portfolio/)_.

**Comment by KayLemba** [comment]
# STATUS: APPROVED :green_circle: :clap: 

Hello  @michael-duke    , 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

HIGHLIGHTS:

- Your project is professional 
- Your repo is professional 
- Well structured files 


Now you can merge this branch and move on :1st_place_medal: 
HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

[OPTIONAL] Kindly add a screenshot to your README file showing your webpage user Interface. You can use extentions like fireshot to capturer the entire page.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by michael-duke** [comment]
@KayLemba Thank you for the optional note 😄 , I actually did that aswell, it was under Website Mockup section in my README.md. Have a good one!
